spring.application.name=sales-service
spring.config.import = optional:configserver:http://localhost:8085
management.endpoints.web.exposure.include=busrefresh,refresh,health,info
spring.kafka.bootstrap-servers=localhost:9092
app.message=this is Sales servers